### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by hcltech84** [hcltech84/gowiki#1]
- [x] #2 
- [x] #3 
- [x] #4 | [Wiki Page](https://github.com/hcltech84/gowiki/wiki/03-%E2%80%90-Setup-MySQL)
- [x] #5  | [Wiki Page](https://github.com/hcltech84/gowiki/wiki/04-%E2%80%90-Interact-with-MySQL)
- [x] #6 | [Wiki Page](https://github.com/hcltech84/gowiki/wiki/05-%E2%80%90-Writing-code-for-the-view-handler)
- [x] #7 | [Wiki Page](https://github.com/hcltech84/gowiki/wiki/06-%E2%80%90-gorilla-mux)
